### ISSUE TITLE
To-Do in V7

### ISSUE THREAD

**Issue by Mettwasser** [WFCD/warframe.rs#21]
- [x] remove all the features, all tho keep/add the following:
   - worldstate
   - market, market_cache
   - profile
- [x] Remove the `warframe::worldstate::prelude` module
- [x] Rename any type called `ApiError` to just `Error`, to follow best practices
- [x] Simplify the example in the README
- [x] Stop making actual requests when testing. Use fixtures instead using [rstest](https://github.com/la10736/rstest).
- [x] Bump MSRV to 1.85 (#23)

**Comment by Mettwasser** [comment]
@CraigEge here we go :D
